### POST kérés egy új feladat létrehozására
POST http://localhost:3000/tasks
Content-Type: application/json

{
    "task": "negyedik"
}

### POST kérés egy új feladat létrehozására
POST http://localhost:3000/users
Content-Type: application/json

{
    "email": "user1@server.hu",
    "name": "user1"
}

### GET kérés az összes feladat lekérdezésére
GET http://localhost:3000/tasks